# Generated by Django 5.1.4 on 2025-01-30 06:23

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('artist', '0002_artist_manager'),
        ('managers', '0006_requiredthing_venue'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('dl91_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event_name', models.CharField(max_length=255)),
                ('event_image', models.ImageField(blank=True, null=True, upload_to='event_images/')),
                ('event_organizer_name', models.CharField(max_length=255)),
                ('event_organizer_contact', models.CharField(max_length=20)),
                ('event_date', models.DateField()),
                ('event_start_time', models.TimeField()),
                ('event_end_time', models.TimeField()),
                ('event_day_of_week', models.CharField(max_length=20)),
                ('event_description', models.TextField()),
                ('event_status', models.CharField(choices=[('Upcoming', 'Upcoming'), ('Ongoing', 'Ongoing'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], max_length=20)),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='artist.artist')),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='managers.manager')),
                ('required_thing', models.ManyToManyField(to='managers.requiredthing')),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='managers.venue')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
