# Generated by Django 5.1.4 on 2025-01-23 06:31

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('dl91_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('profile_picture', models.ImageField(upload_to='artist_profile_pictures/')),
                ('stage_name', models.CharField(max_length=200)),
                ('artist_fields', models.CharField(max_length=200)),
                ('contact', models.CharField(max_length=20)),
                ('instagram_profile', models.URLField()),
                ('spotify_link', models.URLField()),
                ('artist_charge', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
