# Generated by Django 5.1.4 on 2025-01-23 06:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artist', '0001_initial'),
        ('managers', '0005_alter_managerprofileinfo_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='manager',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='managers.manager'),
            preserve_default=False,
        ),
    ]
