# Generated by Django 5.1.4 on 2025-01-13 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='manager',
            name='otp',
            field=models.CharField(default='324135', max_length=10),
        ),
    ]
