# Generated by Django 5.1.4 on 2025-01-13 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managers', '0002_manager_otp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manager',
            name='otp',
            field=models.CharField(blank=True, default='324135', max_length=10, null=True),
        ),
    ]
