# Generated by Django 5.1.4 on 2025-01-13 06:43

import apps.master.helpers.dynamic_filename
import datetime
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managers', '0003_alter_manager_otp'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManagerProfileInfo',
            fields=[
                ('dl91_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('profile', models.ImageField(blank=True, default='default_images/manager_profile.png', null=True, upload_to=apps.master.helpers.dynamic_filename.dynamic_filename_for_manager_profile)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], default='Male', max_length=10)),
                ('date_of_birth', models.DateField(blank=True, default=datetime.date(2025, 1, 1), null=True)),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='managers.manager')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
