# Generated by Django 5.1.4 on 2025-01-13 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managers', '0004_managerprofileinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='managerprofileinfo',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], default='Other', max_length=10),
        ),
    ]
