# Generated by Django 5.1.4 on 2025-01-28 03:41

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managers', '0005_alter_managerprofileinfo_gender'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequiredThing',
            fields=[
                ('dl91_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200, verbose_name='Thing Name')),
                ('price_per_qty', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Price (per Quantity)')),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='managers.manager')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('dl91_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200, verbose_name='Venue Name')),
                ('party_name', models.CharField(max_length=200, verbose_name='Party Name')),
                ('party_contact', models.CharField(max_length=20, verbose_name='Party Contact')),
                ('address', models.TextField(verbose_name='Address')),
                ('city', models.CharField(max_length=100, verbose_name='City')),
                ('pincode', models.CharField(max_length=10, verbose_name='Pincode')),
                ('state', models.CharField(max_length=100, verbose_name='State')),
                ('country', models.CharField(max_length=100, verbose_name='Country')),
                ('venue_charge', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Venue Charge')),
                ('public_strength', models.PositiveIntegerField(verbose_name='Public Strength')),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='managers.manager')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
