# Generated by Django 5.1.4 on 2025-02-14 06:44

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('managers', '0007_contactmessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wine',
            fields=[
                ('dl91_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='managers.manager')),
                ('wine_name', models.CharField(max_length=100, unique=True)),
                ('wine_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('wine_type', models.CharField(choices=[('Red', 'Red'), ('White', 'White'), ('Rosé', 'Rosé'), ('Sparkling', 'Sparkling'), ('Dessert', 'Dessert'), ('Fortified', 'Fortified')], max_length=20)),
                ('alcohol_content', models.FloatField(help_text='Percentage of alcohol content')),
                ('wine_qty_ml', models.PositiveIntegerField(help_text='Quantity in milliliters (ml)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
